// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtaCTqzWj8icaLW2d79vJcQGXmO-2HRcY',
    appId: '1:847529066757:web:04d22f18abc6ac3c69776c',
    messagingSenderId: '847529066757',
    projectId: 'chat-app-10987',
    authDomain: 'chat-app-10987.firebaseapp.com',
    storageBucket: 'chat-app-10987.appspot.com',
    measurementId: 'G-EDQS3X7JD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYCyUskcgErT5TTt2IrcTRS8wGhun1r1c',
    appId: '1:847529066757:android:8e9056156a4a39db69776c',
    messagingSenderId: '847529066757',
    projectId: 'chat-app-10987',
    storageBucket: 'chat-app-10987.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOUqsK2-0WUvFhZibn17Vmqb9IVIz5iww',
    appId: '1:847529066757:ios:59412045fc66307469776c',
    messagingSenderId: '847529066757',
    projectId: 'chat-app-10987',
    storageBucket: 'chat-app-10987.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOUqsK2-0WUvFhZibn17Vmqb9IVIz5iww',
    appId: '1:847529066757:ios:67f041ea67fb167a69776c',
    messagingSenderId: '847529066757',
    projectId: 'chat-app-10987',
    storageBucket: 'chat-app-10987.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
